name: Docker build and push

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'

jobs:
  buildandpush:
    uses: lsc-sde/lsc-sde/.github/workflows/docker-release.yaml@main
    with:
      imageName: awms-keycloak
      directory: products/sde-3rd-party/keycloak/awms-keycloak-extensions
    secrets: inherit
